baseURL = "https://phishbyhannah.com"
languageCode = "en-au"
title = "PHISH"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 30

[params]
  title = "PHISH"
  description = "People in places, above and below the surface."
  language_menu = false
  show_current_lang = false
  title_guard = false
  invertSectionColors = true
  hidedesignbyline = true
  image_options = "webp q90 lanczos photo"
  combine_page_and_site_title = true
  copyright = "Â© PHISH"

  [params.footer]
    showContactIcons = false
    showFooterLinks = false
