languageCode = "en-au"
languageName = "English"
weight = 1
title = "PHISH"

[params]
  displayName = "English"
  isoCode = "en-AU"
  rtl = false
  dateFormat = "2 January 2006"
  description = "People in places, above and below the surface."
