[[main]]
  name = "The Project"
  url = "/project/"
  weight = 10

[[main]]
  name = "Works"
  url = "/works/"
  weight = 20

[[main]]
  name = "Field"
  url = "/field/"
  weight = 30

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 40
