favicon = "brand/phish-logo-darkblue.svg"
images = ["images/phish-waterhabitat-leopardshark-ningaloo-2025.006.jpg"]
title_guard = false
title = "PHISH"
description = "People in places, above and below the surface."
language_menu = false
show_current_lang = false
copyright = "Â© PHISH"
hidedesignbyline = true
invertSectionColors = true
image_options = "webp q90 lanczos photo"
combine_page_and_site_title = true

[[journey]]
  id = "project"
  title = "The Project"
  url = "/project/"

[[journey]]
  id = "works"
  title = "Works"
  url = "/works/"

[[journey]]
  id = "field"
  title = "Field"
  url = "/field/"

[[journey]]
  id = "about"
  title = "Who is PHISH"
  url = "/about/"

[[journey]]
  id = "contact"
  title = "Contact"
  url = "/contact/"

[footer]
  showContactIcons = false
  showFooterLinks = false

[meta]
  keywords = "phish, photography, ocean, field, visual stories"
